Mission waypoints
airmap/qgroundcontrol pull request #10
Opened 2021-08-04 17:45 UTC by jennerl

2021-09-21 17:47 UTC, remster commented on src/Airmap/AirMapFlightPlanManager.cc
> +    QList<QGeoCoordinate> waypoints = QList<QGeoCoordinate>();
seconded

2021-09-21 17:50 UTC, remster commented on src/Airmap/AirMapFlightPlanManager.cc
> +    _flight.coords                  = waypoints;
> This PR creates a flight volume reservation that corresponds to the shape of the outer perimeter of a flight plan instead of a bounding box defined by the maximum and minimum lat/lon extents of the flight path.

I do not see the calculation of the "outer perimiter" (convex hull)? I see that what we submit is a line-string geometry. Can u please elaborate? Does the back-end do it for us?

2021-09-21 17:54 UTC, remster commented on src/Airmap/AirMapFlightPlanManager.cc
> +        waypoints.append(firstWaypoint);
this will add any non-first waypoint twice, I suggest:
```
if (flightPathSegments->count()) {
  waypoints.append{flightPathSegments->value<FlightPathSegment *>(0).coordinate1()};
  for (int i=0, count=flightPathSegments->count(); i < count; i++) {
    waypoints.append{flightPathSegments->value<FlightPathSegment *>(0).coordinate2()};
  }
}
```

2021-09-21 17:56 UTC, remster requested changes
comments left

2021-09-21 19:38 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +    _flight.coords                  = waypoints;
Yes, the backend will turn a bucket of waypoints we submit into a convex hull per Alex.

2021-09-21 20:12 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +        QGeoCoordinate secondWaypoint = currentSegment->coordinate2();
I prefer explicit over implicit, but if this is good practice in modern C++, I want to follow that practice. I'll change in an upcoming PR

2021-09-21 20:22 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +        waypoints.append(firstWaypoint);
suggestion taken, will update in upcoming commit

2021-09-21 20:23 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +    QList<QGeoCoordinate> waypoints = QList<QGeoCoordinate>();
is there then an implicit construction of `waypoints` upon mutation?

2021-09-21 20:40 UTC, keith-bennett-airmap commented on src/Airmap/AirMapFlightPlanManager.cc
> +    QList<QGeoCoordinate> waypoints = QList<QGeoCoordinate>();
No, the construction happens at the declaration unless the compiler can prove that it can omit the construction ahd have no side-effects.

2021-09-21 21:01 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +    QList<QGeoCoordinate> waypoints = QList<QGeoCoordinate>();
I'll be a moderately decent C++ programmers if we stay together a few more years Keith (and Remek)

2021-09-21 23:41 UTC, keith-bennett-airmap commented on src/Airmap/AirMapFlightPlanManager.cc
> +        QGeoCoordinate secondWaypoint = currentSegment->coordinate2();
I had a longer reply but I think I'll just focus on this bit:

> if this is good practice in modern C++, I want to follow that practice.

Here's some supporting info from the broader C++ community about `auto`:
- [Herb Sutter's Guru of the Week #94: Almost Always Auto](https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/)
- In 2014, Herb Sutter gave a talk: ["Back to the Basics! Essentials of Modern C++ Style"](https://youtu.be/xnqTKD8uD64?t=1704). He starts a discussion about `auto` at the linked timestamp and it goes for about 22 minutes if you want to stick to _just_ the bit about `auto` (though the rest of the talk is good info too).
    The takeaways are thus:
    - > [Write code against interfaces, not implementations.](https://youtu.be/xnqTKD8uD64?t=1927)
    
        Here you're writing against the `MissionController` _interface_ and the `platform-sdk` _interface_
    - > [Default to using `auto x = ...`](https://youtu.be/xnqTKD8uD64?t=2336)
    
        Here you're doing `x = ...`.
- A couple years later, Andy Bond gave another talk discussing his experiences with `auto`: ["AAAARGH!? Adopting Almost Always Auto Reinforces Good Habits!?"](https://www.youtube.com/watch?v=ZCGyvPDM0YY). It is, in my opinion, a lot more dry and technical to watch/listen but provides a lot of direct feedback at the code-writing-with-examples level. [At the end](https://youtu.be/ZCGyvPDM0YY?t=2190) he has a couple of tl;dr columns contrasting the benefits with drawbacks.

Regardless, I did approve as-is.

2021-09-22 09:34 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +        waypoints.append(firstWaypoint);
I incorporated this into the latest commit

2021-09-22 10:08 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +        QGeoCoordinate secondWaypoint = currentSegment->coordinate2();
Thanks, Keith. I watched the latter and am watching the former now.

2021-09-23 11:05 UTC, remster approved these changes
But do not merge here - just stand this PR in upstream

2021-09-23 11:12 UTC, remster commented on src/Airmap/AirMapFlightPlanManager.cc
> +        QGeoCoordinate secondWaypoint = currentSegment->coordinate2();
I am enjoying this too! cheerz @keith-bennett-airmap

2021-09-23 12:36 UTC, merged