changes to support the manual authorization state
airmap/qgroundcontrol pull request #12
Opened 2021-09-16 16:03 UTC by jennerl

This PR adds the manual authorization state to the set of states for flight plan evaluations by an airspace authority. Corresponding changes in AirMap's `platform-sdk` codebase support this functionality

2021-09-21 17:40 UTC, remster commented on src/Airmap/AirMapFlightPlanManager.cc
> +        connect(planController, &PlanMasterController::currentPlanFileChanged, this, &AirMapFlightPlanManager::_clearFlightPlan);
what were the consequences of not having it here?

2021-09-21 19:31 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +        connect(planController, &PlanMasterController::currentPlanFileChanged, this, &AirMapFlightPlanManager::_clearFlightPlan);
as a user, to load a new (airmap) flight plan, you had to exit the app then restart

2021-09-21 19:32 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +                    _pollTimer.start(30*1000);
we moved from assuming a pending state would have an automated (LAANC) response to needing to account for a human in the loop. where the human in the loop adds orders of magnitude more time to respond. this change reduces the load on our services to something more manageable.

30s was acceptable to Luke and I believe is good for an automated approval as well.

2021-09-21 19:35 UTC, jennerl commented on src/Airmap/FlightBrief.qml
> +                                    if(_flightPermit === AirspaceFlightPlanProvider.PermitPending || _flightPermit === AirspaceFlightPlanProvider.PermitManualAuthorization)
manual auth vs. automated auth is a distinction our platform services make, so I tried to faithfully follow the conventions in QGC. The concept of a flight permit is outdated (per Luke) and I didn't take the time to excise it in QGC because I didn't spend the time to see what all it touched.

Do you think that effort is warranted?

2021-09-21 20:23 UTC, keith-bennett-airmap commented on src/Airmap/FlightBrief.qml
> +                                    if(_flightPermit === AirspaceFlightPlanProvider.PermitPending || _flightPermit === AirspaceFlightPlanProvider.PermitManualAuthorization)
I think if manual authorization is needed then it should be clear to the end-user in QGC:

1) who is doing manual authorization? airmap? local tower? FAA?

2) how to determine how long the authorization has been in the manual-authorized state -- have I been waiting longer than normal for someone to respond? is there an issue that I need to call in to get unblocked?

2021-09-21 20:30 UTC, jennerl commented on src/Airmap/FlightBrief.qml
> +                                    if(_flightPermit === AirspaceFlightPlanProvider.PermitPending || _flightPermit === AirspaceFlightPlanProvider.PermitManualAuthorization)
Those would make good additions, Keith. AirMap generates an email and sends it to the pilot when he submits the flight plan that needs manual auth. So the pilot does have that info, just not in QGC where it would be most helpful.

2021-09-23 11:19 UTC, remster commented on src/Airmap/AirMapFlightPlanManager.cc
> +                    _pollTimer.start(30*1000);
Won't this loop also continue to service the automated approval? In which case it will non-interactively long. Was anyone in the platform team concerned? Polling the db every few secs will what the db is for. Doing exponential backoff (x2 until it reaches 30) should be easy to manage here - this of course if indeed this timer continues to services the auto-approval

2021-09-23 12:33 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +                    _pollTimer.start(30*1000);
Backoff is a good compromise, I think, and I'll add it today.

This timing does serve both the automated and manual authorization schemes. I did speak with Luke about this and he said that 30s was acceptable and reasonable. If this was in the platform-sdk code, I would not put in such a delay.

2021-09-23 20:33 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +                    _pollTimer.start(30*1000);
@remster added exponential backoff in latest commit. please review at your convenience.

2021-09-30 22:04 UTC, keith-bennett-airmap requested changes
When building in QtCreator I get a non-descriptive build failure around airmap sdk.

```
17:02:21: Running steps for project qgroundcontrol...
17:02:21: Starting: "/home/kbennett/storage/Qt/5.12.10/gcc_64/bin/qmake" /home/kbennett/src/public/qgroundcontrol/qgroundcontrol.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
Info: creating stash file /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/build/build-qgroundcontrol-Desktop_Qt_5_12_10_GCC_64bit-Debug/.qmake.stash
Project MESSAGE: Qt version 5.12.10
Project MESSAGE: Linux build
Project MESSAGE: Daily Build
Project MESSAGE: QGroundControl Development jennerl/flight-auth-ui:cf21ad691 2021-09-30 08:34:09 -0500
Project MESSAGE: Debug flavor
Project MESSAGE: Skipping support for Pairing
Project MESSAGE: Using MAVLink dialect 'ardupilotmega'.
Project MESSAGE: Skipping support for Zeroconf (unsupported platform)
Project MESSAGE: Including support for AirMap
Project MESSAGE: Taisync disabled
Project MESSAGE: Microhard disabled
Project MESSAGE: Including support for video streaming
Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!
17:02:26: The process "/home/kbennett/storage/Qt/5.12.10/gcc_64/bin/qmake" exited normally.
17:02:27: Starting: "/usr/bin/make" -f /home/kbennett/src/public/qgroundcontrol/build/build-qgroundcontrol-Desktop_Qt_5_12_10_GCC_64bit-Debug/Makefile qmake_all
make: Nothing to be done for 'qmake_all'.
17:02:27: The process "/usr/bin/make" exited normally.
17:02:27: Starting: "/usr/bin/make" -j12
rm -rf /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/build/build-qgroundcontrol-Desktop_Qt_5_12_10_GCC_64bit-Debug/libs/airmap-platform-sdk && mkdir -p /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/build/build-qgroundcontrol-Desktop_Qt_5_12_10_GCC_64bit-Debug/libs/airmap-platform-sdk/linux/Qt.5.12 && mkdir -p /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/build/build-qgroundcontrol-Desktop_Qt_5_12_10_GCC_64bit-Debug/libs/airmap-platform-sdk/include/airmap && mkdir -p /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/build/build-qgroundcontrol-Desktop_Qt_5_12_10_GCC_64bit-Debug/libs/airmap-platform-sdk/tmp && wget -q -O /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/build/build-qgroundcontrol-Desktop_Qt_5_12_10_GCC_64bit-Debug/airmap-platform-sdk.deb https://github.com/airmap/platform-sdk/releases/download/2.1.0/airmap-platform-sdk-2.1.0-Linux-x86_64.deb && ar p airmap-platform-sdk.deb data.tar.gz | tar xvz -C /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/build/build-qgroundcontrol-Desktop_Qt_5_12_10_GCC_64bit-Debug/libs/airmap-platform-sdk/tmp/ --strip-components=1 && mv -u /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/build/build-qgroundcontrol-Desktop_Qt_5_12_10_GCC_64bit-Debug/libs/airmap-platform-sdk/tmp/usr/lib/x86_64-linux-gnu/* /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/build/build-qgroundcontrol-Desktop_Qt_5_12_10_GCC_64bit-Debug/libs/airmap-platform-sdk/linux/Qt.5.12/ && mv -u /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/build/build-qgroundcontrol-Desktop_Qt_5_12_10_GCC_64bit-Debug/libs/airmap-platform-sdk/tmp/usr/include/airmap/* /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/build/build-qgroundcontrol-Desktop_Qt_5_12_10_GCC_64bit-Debug/libs/airmap-platform-sdk/include/airmap/ && rm -rf /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/build/build-qgroundcontrol-Desktop_Qt_5_12_10_GCC_64bit-Debug/libs/airmap-platform-sdk/tmp && rm airmap-platform-sdk.deb
rcc /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/qgroundcontrol.qrc
rcc /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/qgcresources.qrc
rcc /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/qgcimages.qrc
rcc /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/resources/InstrumentValueIcons/InstrumentValueIcons.qrc
rcc /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/UnitTest.qrc
rcc /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/src/FirmwarePlugin/APM/APMResources.qrc
rcc /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/src/FirmwarePlugin/PX4/PX4Resources.qrc
rcc /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/src/Airmap/airmap.qrc
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_json_he_IL.ts
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_json_az_AZ.ts
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_json_nl_NL.ts
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_source_tr_TR.ts
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_source_fi_FI.ts
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_source_zh_CN.ts
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_source_no_NO.ts
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_source_sv_SE.ts
Updating '.qm/qgc_json_az_AZ.qm'...
Updating '.qm/qgc_json_nl_NL.qm'...
    Generated 296 translation(s) (271 finished and 25 unfinished)
    Generated 296 translation(s) (0 finished and 296 unfinished)
Updating '.qm/qgc_json_he_IL.qm'...
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_source_ko_KR.ts
    Generated 296 translation(s) (0 finished and 296 unfinished)
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_source_de_DE.ts
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_json_it_IT.ts
Updating '.qm/qgc_json_it_IT.qm'...
    Generated 296 translation(s) (0 finished and 296 unfinished)
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_json_ja_JP.ts
Updating '.qm/qgc_source_tr_TR.qm'...
Updating '.qm/qgc_source_sv_SE.qm'...
Updating '.qm/qgc_source_no_NO.qm'...
Updating '.qm/qgc_source_fi_FI.qm'...
Updating '.qm/qgc_source_zh_CN.qm'...
Updating '.qm/qgc_json_ja_JP.qm'...
    Generated 296 translation(s) (0 finished and 296 unfinished)
    Generated 3070 translation(s) (0 finished and 3070 unfinished)
    Ignored 3 untranslated source text(s)
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_source_pt_PT.ts
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_source_fr_FR.ts
    Generated 3070 translation(s) (0 finished and 3070 unfinished)
    Ignored 3 untranslated source text(s)
    Generated 3070 translation(s) (0 finished and 3070 unfinished)
    Ignored 3 untranslated source text(s)
    Generated 3070 translation(s) (0 finished and 3070 unfinished)
    Ignored 3 untranslated source text(s)
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_source_pl_PL.ts
    Generated 3070 translation(s) (1 finished and 3069 unfinished)
    Ignored 3 untranslated source text(s)
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_az_AZ.ts
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_source_he_IL.ts
Updating '.qm/qgc_source_de_DE.qm'...
lrelease /opt/kbennett-ll/oldroot/home/kbennett/src/public/qgroundcontrol/translations/qgc_source_az_AZ.ts
Updating '.qm/qgc_source_ko_KR.qm'...
Updating '.qm/qgc_az_AZ.qm'...
    Generated 639 translation(s) (0 finished and 639 unfinished)
    Generated 3070 trans [...]

2021-10-01 14:17 UTC, remster approved these changes
LGTM

2021-10-01 14:50 UTC, jennerl commented on QGCExternalLibs.pri
> +        AIRMAP_PLATFORM_SDK_URL = "https://github.com/airmap/platform-sdk/releases/download/2.1.0/airmap-platform-sdk-2.1.0-Linux-x86_64.deb"
Looking into this now

2021-10-01 14:53 UTC, merged