Fix AirMap telemetry updates
airmap/qgroundcontrol pull request #2
Opened 2021-01-22 19:44 UTC by jennerl

2021-01-22 19:45 UTC, jennerl commented on src/MissionManager/MissionController.cc
> +                            minAlt = maxAlt = alt;
On takeoff, initialize min and max altitude to the takeoff altitude. The behavior before this change was that the min and max altitudes would always be stuck on their initial values of `QGCGeoBoundingCube::MinAlt` and `QGCGeoBoundingCube::MaxAlt` respectively.

2021-01-22 19:45 UTC, jennerl commented on src/MissionManager/MissionController.cc
> +                        double alt = 0.0;
get the current item's altitude, if available. Somehow, `pSimpleItem->coordinate()->altitude()` is incorrect but the altitude in `pSimpleItem->altitude()` is correct.

2021-02-01 13:53 UTC, remster commented on src/MissionManager/MissionController.cc
> +                            alt = pSimpleItem->altitude()->rawValue().toDouble();   // for some reason, the item's coordinate().altitude() is out of sync with the altitude()
yes - `missionItem.coordinate().altitude()` is - "undefined" - i.e.: hard to tell what it means and you're right, `missionItem.altitude()`is meaningful, but be very very careful - this number can have at least [three references](https://github.com/airmap/qgroundcontrol/blob/master/src/QmlControls/QGroundControlQmlGlobal.h#L51). You can inspect what the reference is by calling 
```
pSimpleItem->altitudeMode
```
Importantly.. what does it need to be?
I understand this is part of flight plan submission? Please amend the PR's description to explain the scope.

2021-02-01 13:53 UTC, remster requested changes
pls handle altitude references as per comment

2021-02-01 14:08 UTC, jennerl commented on src/MissionManager/MissionController.cc
> +                        double alt = 0.0;
The expectation is for it to be altitude above ground level. This matches what the platform is expecting. I'll take a closer look here to make sure it's a match. Empirically, the telemetry being reported is shown correctly in AirMap's telemetry views, so it should be a good match.

2021-02-01 14:09 UTC, jennerl commented on src/MissionManager/MissionController.cc
> +                            alt = pSimpleItem->altitude()->rawValue().toDouble();   // for some reason, the item's coordinate().altitude() is out of sync with the altitude()
The expectation is for it to be altitude above ground level. This matches what the platform is expecting. I'll take a closer look here to make sure it's a match. Empirically, the telemetry being reported is shown correctly in AirMap's telemetry views, so it should be a good match.

2021-02-01 18:58 UTC, jennerl commented on src/MissionManager/MissionController.cc
> +                            alt = pSimpleItem->altitude()->rawValue().toDouble();   // for some reason, the item's coordinate().altitude() is out of sync with the altitude()
This function is agnostic of altitude mode. Whatever altitude mode is set for the mission is passed to the geo bounding cube representing the mission's physical extents.

Later, in AirMapFlightPlanManager::_collectFlightData(), we simply take whatever altitudes are stored in the bounding cube and pass those onto the platform as part of the flight plan. That part does need help adjusting for which altitude reference the user selected when planning the mission.

2021-02-02 15:59 UTC, jennerl commented on src/MissionManager/TakeoffMissionItem.cc
>                  _settingsItem->setCoordinate(homePosition);
this line specifically discards altitude information in `homePosition` so the next line adds it back

2021-02-02 16:01 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +    _flight.maxAltitude         = (_planController->missionController()->globalAltitudeMode() == QGroundControlQmlGlobal::AltitudeModeRelative) ? maxMissionAltitude : maxMissionAltitude - _flight.tak
AirMap expects AGL altitudes, so adjust if the altitude mode isn't relative

2021-02-02 16:09 UTC, remster commented on src/Airmap/AirMapFlightPlanManager.cc
> +    _flight.maxAltitude         = (_planController->missionController()->globalAltitudeMode() == QGroundControlQmlGlobal::AltitudeModeRelative) ? maxMissionAltitude : maxMissionAltitude - _flight.tak
I think there is more complexity here;
- AGL isn't the same as relative - agl is above ground below the drone, relative is relative to takeoff irrespective of any terrain model; 
- You're assuming, if the mode isn't relative, it is absolute. That's also not the case - pls check other modes.
- You're assuming `_flight.takeoffCoord.altitude()` is known at the time of calling. This altitude is necessarily from a DEM and fetching it is both asynchronous and fallible. From experience, should `MissionController::readyForSaveState() == VisualMissionItem::ReadyForSave` then you can trust these altitudes and submit a flight plan. When this bit of code specifically called?

2021-02-02 17:22 UTC, remster commented on src/Airmap/AirMapFlightPlanManager.cc
> +    _flight.maxAltitude         = (_planController->missionController()->globalAltitudeMode() == QGroundControlQmlGlobal::AltitudeModeRelative) ? maxMissionAltitude : maxMissionAltitude - _flight.tak
Just occurred to me - if `_flight` is specifically collected for the purpose of submitting the flight plan - and i assume it is - please name these altitudes explicitly. Suggest `s/_flight.maxAltitude/_flight.maxAltitudeAboveTakeoff` - i really hate it about QGC that it never specifies the units or references.

2021-02-02 18:42 UTC, remster commented on src/MissionManager/TakeoffMissionItem.cc
>                  _settingsItem->setCoordinate(homePosition);
I don't think this is correct. The `_settingsItem` works out the terrain altitude into its MissionSettingsItem::plannedHomePositionAltitude` - this is [specifically terrain](https://github.com/airmap/qgroundcontrol/blob/master/src/MissionManager/MissionSettingsItem.cc#L286). 

Please explain why are you doing this and what's the reading? I feel really insecure with a word `altitude` - it always has to be unambiguously referenced. 

Either way, i don't think you wanna do it, i think you want to rely on `plannedHomePositionAltitude`

2021-02-02 18:46 UTC, remster commented on src/MissionManager/MissionController.cc
> +                        if (!pSimpleItem->altitude()->rawValue().isNull()) {
you better also check `qIsNan(pSimpleItem->altitude()->rawValue().toDouble())`

2021-02-02 18:47 UTC, remster commented on src/MissionManager/MissionController.cc
> +                            minAlt = maxAlt = alt;
please - in comments and by naming variables under your control, make it clear what reference points these altitudes have.

2021-02-02 20:21 UTC, jennerl commented on src/MissionManager/MissionController.cc
> +                            minAlt = maxAlt = alt;
these are minimum and maximum altitudes contained in the waypoints. they intentionally pay no heed to the reference since QGC does not consider an altitude reference for this bounding box.

for AirMap's purposes, we do care about the reference, so we handle that later in AirMap specific code in this project.

2021-02-02 20:22 UTC, jennerl commented on src/MissionManager/MissionController.cc
> +                        if (!pSimpleItem->altitude()->rawValue().isNull()) {
thank you..good catch

2021-02-02 23:32 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +    _flight.maxAltitude         = (_planController->missionController()->globalAltitudeMode() == QGroundControlQmlGlobal::AltitudeModeRelative) ? maxMissionAltitude : maxMissionAltitude - _flight.tak
Updated variable name to be more specific.

2021-02-02 23:36 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +    _flight.maxAltitude         = (_planController->missionController()->globalAltitudeMode() == QGroundControlQmlGlobal::AltitudeModeRelative) ? maxMissionAltitude : maxMissionAltitude - _flight.tak
Re: timing and validity of altitude:

we're updating the flight plan bounds based on `MissionController` emitting `missionBoundingCubeChanged()` which [happens](https://github.com/mavlink/qgroundcontrol/blob/7033dddcb8b8f8a25400e97181f5c889f2f6722c/src/MissionManager/MissionController.cc#L2565) after the user updates the flight plan in QGC's planning interface.

By that time, `MissionController` has also updated `_takeoffCoordinate`

2021-02-03 01:38 UTC, akontsevich commented on libs/airmapd/linux/Qt.5.12/libairmap-cpp.so
> +libairmap-cpp.so.0.0.1
Why binaries are there?

2021-02-03 01:54 UTC, akontsevich reviewed
Have some questions and concerns

2021-02-03 01:54 UTC, akontsevich commented on src/Airmap/AirMapFlightPlanManager.cc
> +    _flight.maxAltitude         = (_planController->missionController()->globalAltitudeMode() == QGroundControlQmlGlobal::AltitudeModeRelative) ? maxMissionAltitude : maxMissionAltitude - _flight.tak
I think AGL altitude calculation should be more complex there, similar to this one: [ElevationProfile.qml#L181-L199](https://github.com/airmap/AirBoss/blob/master/custom/res/AirBoss/PlanView/ElevationProfile.qml#L181-L199)

2021-02-03 01:54 UTC, akontsevich commented on src/Airmap/AirMapManager.cc
> +        configuration.telemetry.port = 16060;
Should not be these const defined in header?

2021-02-03 13:27 UTC, jennerl commented on libs/airmapd/linux/Qt.5.12/libairmap-cpp.so
> +libairmap-cpp.so.0.0.1
this is the initial method of delivery of `platform-sdk` into qgroundcontrol, and it repeats how we delivered our prior integration with qgroundcontrol. I'm working on packaging `platform-sdk` as a downloadable package that qgroundcontrol build system can download and unpack, but that will be a follow-on effort.

2021-02-03 13:30 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +    _flight.maxAltitude         = (_planController->missionController()->globalAltitudeMode() == QGroundControlQmlGlobal::AltitudeModeRelative) ? maxMissionAltitude : maxMissionAltitude - _flight.tak
yes, good idea. I will generalize that function and use it to compute AGL altitudes.

2021-02-03 13:38 UTC, jennerl commented on src/Airmap/AirMapManager.cc
> +        configuration.telemetry.port = 16060;
changed as you suggested.

2021-02-03 13:39 UTC, jennerl commented on src/MissionManager/TakeoffMissionItem.cc
>                  _settingsItem->setCoordinate(homePosition);
I removed setting the alttiude here.

2021-02-03 14:02 UTC, remster commented on src/MissionManager/MissionController.cc
> +                            minAlt = maxAlt = alt;
ack!

2021-02-03 20:17 UTC, akontsevich commented on src/Airmap/AirMapManager.cc
> +        configuration.telemetry.port = 16060;
And what commit is it? Please put links to fixes.

2021-02-03 20:57 UTC, akontsevich commented on libs/airmapd/linux/Qt.5.12/libairmap-cpp.so
> +libairmap-cpp.so.0.0.1
Still looks strange however. Usually binaries are not put into version controls but links to sources and submodules. What about Qt 5.15: will need to rebuild the libs? What about Android versions, different ABIs, processor capacity (32/64 bit), etc?

2021-02-03 21:56 UTC, jennerl commented on libs/airmapd/linux/Qt.5.12/libairmap-cpp.so
> +libairmap-cpp.so.0.0.1
Yes, all good points and I do agree. We have other tickets to do this work, for example https://airmap.atlassian.net/browse/PLAT-5352.

I could combine that work with this PR before it goes into the main QGC project as a PR..I'll leave that for the team to decide what's best.

2021-02-03 22:05 UTC, akontsevich commented on libs/airmapd/linux/Qt.5.12/libairmap-cpp.so
> +libairmap-cpp.so.0.0.1
I see

2021-02-04 14:56 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +    _flight.maxAltitude         = (_planController->missionController()->globalAltitudeMode() == QGroundControlQmlGlobal::AltitudeModeRelative) ? maxMissionAltitude : maxMissionAltitude - _flight.tak
I removed all of this code after confirming the altitudes we're getting from QGC in the form of the bounding cube are all relative to a takeoff altitude. So this code is not necessary.

2021-02-04 14:57 UTC, jennerl commented on src/Airmap/AirMapFlightPlanManager.cc
> +    _flight.maxAltitude         = (_planController->missionController()->globalAltitudeMode() == QGroundControlQmlGlobal::AltitudeModeRelative) ? maxMissionAltitude : maxMissionAltitude - _flight.tak
after investigating, the altitudes we're getting from QGC are always relative to a takeoff altitude which is what the AirMap platform is expecting. So I'm not going to consider altitude references further for this specific PR

2021-03-22 17:18 UTC, jennerl commented
Accepted into QGC main repo, so closing PR on this repo

2021-03-22 17:18 UTC, closed without merging