Keith/stability fixes/qgc cache worker
airmap/qgroundcontrol pull request #6
Opened 2021-04-09 13:12 UTC by keith-bennett-airmap

This fixes racey access on `QGCCacheWorker::_taskQueue` and `QGCCacheWorker::_valid`. It also has some slight refactoring to help readability and help ensure that exceptions thrown don't cause leaks in SQLite.

![QGCCacheWorker _taskQueue is racey](https://user-images.githubusercontent.com/72767521/114184940-bdebc500-990a-11eb-8b5a-d015e33cf52d.png)

![QGCCacheWorker _valid is racey](https://user-images.githubusercontent.com/72767521/114184948-c04e1f00-990a-11eb-9e5f-2095adff9772.png)

2021-04-09 14:01 UTC, akontsevich commented
Interesting! What tool is used to draw these race conditions?

2021-04-09 14:08 UTC, keith-bennett-airmap commented
I hand drew the diagrams using draw.io which was renamed to [diagrams.net](https://www.diagrams.net/).

2021-04-09 14:55 UTC, remster commented
In the description it is unclear whether you are describing the problem or the solution. Please make that clear. 
You say "mutex" should be used - which suggests it's part of the solution, yet the 3rd diagram clearly shows a problem - that your solution is leaving behind? Probably not.

2021-04-09 14:57 UTC, remster commented on src/QtLocationPlugin/QGCTileCacheWorker.cpp
>      if(this->isRunning()) {
you need to explain (PR comment) why removing the `unlock` will not cause a deadlock around here. - you are delaying the release of the mutex. I assume either `_waitc.wakeAll()` and/or `this->start()` can be called with that mutex down.

2021-04-09 14:58 UTC, remster commented on src/QtLocationPlugin/QGCTileCacheWorker.cpp
> +QGCCacheWorker::_connectDB()
:+1:

2021-04-09 15:01 UTC, keith-bennett-airmap commented
> In the description it is unclear whether you are describing the problem or the solution. Please make that clear.

The diagrams show the problem. The diff solves the problem.

> You say "mutex" should be used - which suggests it's part of the solution, yet the 3rd diagram clearly shows a problem - that your solution is leaving behind? Probably not.

The `_mutex` needs to be used. The diff solves the problem by using it.

2021-04-09 15:01 UTC, remster commented on src/QtLocationPlugin/QGCTileCacheWorker.h
> +    QMutex                          _mutex;
call it after the resource it is protecting? `_taskQueueMutex`

2021-04-09 15:04 UTC, remster commented on src/QtLocationPlugin/QGCTileCacheWorker.cpp
>          if(_taskQueue.count()) {
was this the unguarded count on the diagram? You will later raise a separate PR against upstream - maybe contextualise the diagram pasting into a comment like this one?

2021-04-09 15:05 UTC, remster commented
All clean here - just some nits and advise how to "sale" it to the qgc community.

2021-04-09 15:09 UTC, remster commented
> > In the description it is unclear whether you are describing the problem or the solution. Please make that clear.
> 
> The diagrams show the problem. The diff solves the problem.

Please make it explicit when u submit the outgoing PR - i had to ponder

2021-04-09 15:09 UTC, remster requested changes
can't merge here - this PR needs to be raised against upstream and merged there - in case that's wasnt clear.

2021-04-09 15:24 UTC, keith-bennett-airmap commented on src/QtLocationPlugin/QGCTileCacheWorker.cpp
>      if(this->isRunning()) {
Ahh whoops. It won't cause a deadlock but may cause a stall.

`QWaitCondition` has its own internal mutex. That mutex is only used to guard the list of threads that are waiting on the condition.

Calling `wakeAll()` will lock the internal mutex. Then it will broadcast the wakeup to all threads. Finally it will unlock the internal mutex before leaving. It doesn't know about QGC's mutex so that remains locked for the entire duration.

On the other side of the condition, the waiting thread will unlock QGC's mutex and then lock the internal mutex and gives the internal mutex to pthread who then unlocks it. When the thread wakes up, the internal mutex gets unlocked, QGC's mutex is re-locked, and finally the thread returns. There's no deadlock here because the lock order is consistent between the two threads: the thread issuing the wake-up can safely hold both locks, while the thread waking-up will only ever hold one of them at a time.

See `5.12.10/Src/qtbase/src/corelib/thread/qwaitcondition_unix.cpp`, lines `197-204` for the definition of `wakeAll()`, lines `205-231` for definitions of `wait()`, and lines `139-171` for the definition of the conditional-wait.

2021-04-09 15:26 UTC, keith-bennett-airmap commented on src/QtLocationPlugin/QGCTileCacheWorker.cpp
>          if(_taskQueue.count()) {
> was this the unguarded count on the diagram?

Correct.

> You will later raise a separate PR against upstream - maybe contextualise the diagram pasting into a comment like this one?

Are you saying to duplicate the diagram in the PR description and also in a separate comment? Or should it be preferred to be only in a comment next to this diff?

2021-04-09 15:34 UTC, keith-bennett-airmap commented on src/QtLocationPlugin/QGCTileCacheWorker.h
> +    QMutex                          _mutex;
https://github.com/airmap/qgroundcontrol/pull/6/commits/28fb4c2f0277ba3f768a34085f4982f38030f34e

2021-04-09 15:34 UTC, keith-bennett-airmap commented on src/QtLocationPlugin/QGCTileCacheWorker.cpp
>      if(this->isRunning()) {
https://github.com/airmap/qgroundcontrol/pull/6/commits/28fb4c2f0277ba3f768a34085f4982f38030f34e

2021-04-09 16:32 UTC, keith-bennett-airmap commented
Please consider these updated diagrams which include descriptions of both the problem and the solution presented by the pull request

![QGCCacheWorker _taskQueue is racey](https://user-images.githubusercontent.com/72767521/114211786-af130b80-9926-11eb-8645-f731877b6bed.png)

![QGCCacheWorker _valid is racey](https://user-images.githubusercontent.com/72767521/114211803-b33f2900-9926-11eb-843e-b7401d5aab86.png)

2021-04-09 16:36 UTC, remster commented on src/QtLocationPlugin/QGCTileCacheWorker.cpp
>          if(_taskQueue.count()) {
I think i am suggesting to put it only in the per-line comment to give it context. Other changes in the PR address other problems - like throwing paths or code sharing.

2021-04-12 15:49 UTC, keith-bennett-airmap commented
PR opened in mavlink fork -> https://github.com/mavlink/qgroundcontrol/pull/9588

2021-04-12 15:49 UTC, closed without merging